update cache conditions and install ssh server on ec2

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -31,27 +31,47 @@ jobs:
         with:
           terraform_wrapper: false
 
-      - name: Install SSH Client
-        run: sudo apt-get install -y openssh-client
+      - name: Cache SSH Client Installation
+        id: cache_ssh_client
+        run: |
+          if ! command -v ssh &> /dev/null; then
+            echo "SSH client not found. Installing..."
+            sudo apt-get update
+            sudo apt-get install -y openssh-client
+          else
+            echo "SSH client is already installed."
+          fi
+
+      - name: Check for SSH Key Cache
+        id: check_ssh_cache
+        run: |
+          if [ -f ~/.ssh/github-actions-key ]; then
+            echo "SSH key cache exists."
+            echo "ssh_cache_exists=true" >> $GITHUB_ENV
+          else
+            echo "ssh_cache_exists=false" >> $GITHUB_ENV
+          fi
 
       - name: Generate SSH Key
+        if: ${{ env.ssh_cache_exists }} == 'false'
         run: |
-          ssh-keygen -t rsa -b 4096 -f ~/.ssh/${{ env.SSH_KEY_NAME }} -N "" || echo "SSH key already exists"
+          ssh-keygen -t rsa -b 4096 -f ~/.ssh/github-actions-key -N "" || echo "SSH key already exists"
 
       - name: Set up SSH Key
         run: |
           mkdir -p ~/.ssh
           chmod 700 ~/.ssh
-          cat ~/.ssh/${{ env.SSH_KEY_NAME }}.pub | tee -a ~/.ssh/authorized_keys
+          cat ~/.ssh/github-actions-key.pub | tee -a ~/.ssh/authorized_keys
 
       - name: Cache SSH Keys
+        if: ${{ env.ssh_cache_exists }} == 'false'
         uses: actions/cache@v3
         with:
-          path: ~/.ssh/${{ env.SSH_KEY_NAME }}*
-          key: ${{ runner.os }}-ssh-keys-${{ hashFiles(format('~/.ssh/%s.pub', env.SSH_KEY_NAME)) }}
+          path: ~/.ssh/github-actions-key*
+          key: ${{ runner.os }}-ssh-keys-${{ hashFiles('~/.ssh/github-actions-key.pub') }}
           restore-keys: |
             ${{ runner.os }}-ssh-keys-
-
+              
       - name: Terraform Init
         run: terraform init
       
@@ -67,7 +87,18 @@ jobs:
         id: instance_ip
         run: echo "INSTANCE_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV
 
+      - name: Check for Terraform State Cache
+        id: check_tf_cache
+        run: |
+          if [ -d .terraform ]; then
+            echo "Terraform state cache exists."
+            echo "tf_cache_exists=true" >> $GITHUB_ENV
+          else
+            echo "tf_cache_exists=false" >> $GITHUB_ENV
+          fi
+
       - name: Cache Terraform State
+        if: ${{ env.tf_cache_exists }} == 'false'
         uses: actions/cache@v3
         with:
           path: .terraform/
