debug

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -85,7 +85,7 @@ jobs:
       - name: Add EC2 to Known Hosts
         run: |
           echo "INSTANCE_IP: ${{ env.INSTANCE_IP }}"
-          ssh-keyscan -H "${{ env.INSTANCE_IP }}" > ~/.ssh/known_hosts
+          ssh-keyscan -H "${{ env.INSTANCE_IP }}" -v > ~/.ssh/known_hosts || echo "Failed to add host key"
           cat ~/.ssh/known_hosts
 
       - name: Cache Ansible Installation
